package com.fitness.projectluna.model

enum class TypeException {
  REPOSITORY_EXCEPTION,
  SERVICE_EXCEPTION,
  CONTROLLER_EXCEPTION,
  VALIDATION_EXCEPTION,
  UNKNOWN_EXCEPTION,
  UNAUTHORIZED_EXCEPTION
}