package com.fitness.projectluna.model

enum class TypeException {
  REPOSITORY_EXCEPTION,
  SERVICE_EXCEPTION,
  CONTROLLER_EXCEPTION,
  VALIDATION_EXCEPTION,
  UNKNOWN_EXCEPTION,
  UNAUTHORIZED_EXCEPTION,
  TRAINER_ALREADY_EXISTS,
  PASSWORD_INCORRECT,
  INVALID_REQUEST,
  PROCESS_NOT_IMPLEMENTED,
  PUBLISHER_ERROR,
  SERVICE_UNAVAILABLE_TYPE,
  PROCESS_VALIDATED,
  INVALID_PASSWORD,
}