name: Java CI with Gradle

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Validate Gradle wrapper
        run: ./gradlew wrapper --gradle-version 7.2
      - name: Build with Gradle
        run: ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs
      - name: DeepSource Test Coverage Action
        uses: DeepSourceCorp/test-coverage-action@v1.1.2
        with:
          key: java
          coverage-file: ./build/reports/jacoco/test/jacocoTestReport.xml
          dsn: ${{ secrets.DEEP_SOURCE_DSN }}
          fail-ci-on-error: true
          commit-sha: ${{ github.event.pull_request.head.sha }}
