name: CI lunasoft

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build and generate coverage report
        run: ./gradlew build

      - name: DeepSource Test Coverage Action
        uses: DeepSourceCorp/test-coverage-action@v1.1.2
        with:
          key: java
          coverage-file: ./build/reports/jacoco/test/jacocoTestReport.xml
          dsn: ${{ secrets.DEEP_SOURCE_DSN }}
          fail-ci-on-error: true
          commit-sha: ${{ github.event.pull_request.head.sha }}
