name: CI lunasoft

on:
  push:
    branches: ["develop", "main"]
  pull_request:
    branches: ["develop", "main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build and generate coverage report
        run: ./gradlew build

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash) -f build/reports/jacoco/test/jacocoTestReport.xml